_target_: ${csi}.modules.base_stream.BaseStream
encoder:
  _target_: ${csi}.modules.VitWithAttnVitPose
  img_size: 192
  color_range: [0, 1]
  cfg_path: ${resources.vitpose_cfg}
  checkpoint: ${resources.vitpose_ckpt}
  drop_path_rate: 0.2
neck:
  _target_: ${csi}.modules.TemporalConvNeck
  in_channels: 384
  out_channels: 1024
  bottle_channels: 512
  n_class: 1296
  with_header: True,
  pooling: max
  dropout: 0.2
decoder:
  _target_: ${csi}.modules.TransformerDecoder
  n_class: 1296
  d_model: 1024
  n_heads: 8
  n_layers: 6
  d_feedforward: 2048
  dropout: 0.5
