_target_: ${csi}.modules.base_stream.BaseStream
encoder:
  _target_: ${csi}.modules.ViTAttnEncoder
  # arch: vit-base-p32
  # checkpoint: resources/vit-base/vit-base-p32_in21k-pre-3rdparty_ft-64xb64_in1k-384_20210928-9cea8599.pth
  arch: vit-base-p16
  checkpoint: resources/vit-base/vit-base-p16_in21k-pre-3rdparty_ft-64xb64_in1k-384_20210928-98e8652b.pth
  # checkpoint: resources/vit-base/vit-base-p16_pt-32xb128-mae_in1k_20220623-4c544545.pth

neck:
  _target_: ${csi}.modules.TemporalConvNeck
  in_channels: 768
  out_channels: 512
  bottle_channels: 256
  n_class: 1296
  with_header: True,
  pooling: max
  dropout: 0.2
decoder:
  _target_: ${csi}.modules.TransformerDecoder
  n_class: 1296
  d_model: 512
  n_heads: 8
  n_layers: 4
  d_feedforward: 1024
  dropout: 0.2
