_target_: ${csi}.modules.base_stream.BaseStream
encoder:
  _target_: ${csi}.modules.ViTEncoderWithAttentionHG
  # vit_model: faceWinKawaks/vit-small-patch16-224book/deit-tiny-patch16-224
  # vit_model: WinKawaks/vit-small-patch16-224
  # vit_model: google/vit-base-patch16-224
  vit_model: facebook/deit-small-patch16-224
  use_cls_token: false
neck:
  _target_: ${csi}.modules.TemporalConvNeck
  in_channels: 384
  out_channels: 1024
  bottle_channels: 512
  n_class: 1296
  with_header: True,
  pooling: max
  dropout: 0.2
decoder:
  _target_: ${csi}.modules.TransformerDecoder
  n_class: 1296
  d_model: 1024
  n_heads: 8
  n_layers: 4
  d_feedforward: 2048
  dropout: 0.2
